name: Check

on:
  push:
    # XXX: this must match `paths` in ./seed.yaml
    paths-ignore: &paths-ignore
      - flake.lock
      - flake.nix
      - mkseed.nix
      - .github/workflows/seed.yaml
  pull_request:
    paths-ignore: *paths-ignore
  workflow_run:
    workflows:
      - Seed
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
      - run: nix flake check --print-build-logs
